name: Issue to Email
on:
  issues:
    types: [opened]
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const issueTitle = context.payload.issue.title;
            //  Add logic here to extract relevant information
            //  from the issueBody.
            const approverEmail = "approver@example.com"; // Set the approver's email

            //  Use a 3rd party action to send the email.
            //  There are many actions available on GitHub Marketplace
            //  Example (you'll need to configure it):
            await github.rest.mail.send({
              to: approverEmail,
              subject: issueTitle,
              message: issueBody,
            });
